"""C-to-Rust conversion tools for MikroE Click packages."""

from rusty_ai_converter.catalog import (
    CatalogError,
    CatalogFormatError,
    CatalogReadError,
    load_catalog,
    parse_catalog_data,
)
from rusty_ai_converter.archive import (
    ArchiveInspectionError,
    classify_archive_path,
    inspect_archive,
)
from rusty_ai_converter.download import (
    DownloadError,
    download_package,
    load_cached_archive,
)
from rusty_ai_converter.models import (
    ARCHIVE_FILE_ROLES,
    SOURCE_TEXT_PURPOSES,
    ArchiveFile,
    CachedArchive,
    ExampleMetadata,
    ManifestLibrary,
    PackageCatalog,
    PackageInventory,
    PackageManifest,
    PackageRecord,
    SourceBundle,
    SourceTextFile,
)
from rusty_ai_converter.source import SourceSelectionError, build_source_bundle
from rusty_ai_converter.parsing import (
    CParserError,
    ClickPackageIR,
    parse_c_file,
    parse_source_bundle,
)
from rusty_ai_converter.sdk_mapping import (
    CallResolution,
    SdkFunction,
    SdkFunctionMapping,
    SdkIndexError,
    SdkMappingDatabase,
    TranslationPlan,
    build_sdk_mapping_database,
    build_translation_plan,
)
from rusty_ai_converter.context import (
    DEFAULT_MAX_REQUEST_BYTES,
    PROMPT_VERSION,
    ContextBuildError,
    ModelMessage,
    ModelRequest,
    build_model_request,
)
from rusty_ai_converter.model_client import (
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_OPENAI_MODEL,
    DEFAULT_REASONING_EFFORT,
    DEFAULT_TIMEOUT_SECONDS,
    FakeModelClient,
    ModelClient,
    ModelClientConfigurationError,
    ModelClientError,
    ModelConversion,
    ModelUsage,
    OpenAIModelClient,
)
from rusty_ai_converter.model_output import (
    COVERAGE_KINDS,
    COVERAGE_STATUSES,
    CoverageEntry,
    ModelOutput,
    ModelOutputError,
    model_output_response_schema,
    parse_model_output,
)

__all__ = [
    "CatalogError",
    "CatalogFormatError",
    "CatalogReadError",
    "ARCHIVE_FILE_ROLES",
    "SOURCE_TEXT_PURPOSES",
    "ArchiveFile",
    "ArchiveInspectionError",
    "CachedArchive",
    "CallResolution",
    "COVERAGE_KINDS",
    "COVERAGE_STATUSES",
    "ContextBuildError",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "DEFAULT_MAX_REQUEST_BYTES",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_REASONING_EFFORT",
    "DEFAULT_TIMEOUT_SECONDS",
    "CParserError",
    "ClickPackageIR",
    "CoverageEntry",
    "DownloadError",
    "ExampleMetadata",
    "ManifestLibrary",
    "FakeModelClient",
    "ModelClient",
    "ModelClientConfigurationError",
    "ModelClientError",
    "ModelConversion",
    "ModelMessage",
    "ModelOutput",
    "ModelOutputError",
    "ModelRequest",
    "ModelUsage",
    "OpenAIModelClient",
    "PackageCatalog",
    "PackageInventory",
    "PackageManifest",
    "PackageRecord",
    "PROMPT_VERSION",
    "SourceBundle",
    "SourceSelectionError",
    "SourceTextFile",
    "SdkFunction",
    "SdkFunctionMapping",
    "SdkIndexError",
    "SdkMappingDatabase",
    "TranslationPlan",
    "build_source_bundle",
    "build_sdk_mapping_database",
    "build_model_request",
    "build_translation_plan",
    "classify_archive_path",
    "download_package",
    "inspect_archive",
    "load_catalog",
    "load_cached_archive",
    "parse_catalog_data",
    "parse_c_file",
    "model_output_response_schema",
    "parse_model_output",
    "parse_source_bundle",
]

__version__ = "0.1.0"
